# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TwitterClient' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
#  pod 'Parse'
#  pod 'SendGrid', :git => 'https://github.com/scottkawai/sendgrid-swift.git'
  pod 'AFNetworking', '3.0.0'
  pod 'BDBOAuth1Manager', '2.0.0'
  pod 'DateToolsSwift'
    

  # Pods for TwitterClient

end
